on:
  push:
    branch:
      - main

jobs:
  shellcheck:
    name: Proselint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Proselint
      uses: dhruvmanila/action-proselint@main
